### ISSUE TITLE
リソース設計

### ISSUE THREAD

**Issue by natsuto6** [natsuto6/ruby-uchi#16]
- エレベーターピッチ
https://bootcamp.fjord.jp/products/17514

- ペーパープロトタイプ
https://bootcamp.fjord.jp/products/17827

- DB設計
https://github.com/natsuto6/ruby-uchi/issues/17

<details><summary>1回目の提出物</summary><div>

| Method| Path | Description |
|:----|:----|:----|
|GET |/ |トップ画面を表示（ログインしていればマイページを、ログインしていなければトップページを表示） |
|GET |/signup |ユーザー登録画面の表示 |
|POST |/signup |ユーザー登録処理の実行 |
|GET |/login|ログイン画面の表示 |
|POST |/login|ログイン処理の実行 |
|POST |/logout|ログアウト処理の実行 |
|GET |/password_resets/new|パスワード再設定用メールアドレス入力画面の表示 |
|POST |/password_resets|パスワード再設定メールの送信処理の実行 |
|GET |/password_resets/{token}/edit|新しいパスワード入力画面の表示 |
|PATCH |/password_resets/{token}|新しいパスワードでの更新処理の実行 |
|GET |/users/{userId}|ユーザー詳細画面の表示（マイページ） |
|GET |/users/{userId}/edit|ユーザー情報編集画面の表示 |
|PATCH |/users/{userId}|ユーザー情報更新処理の実行 |
|DELETE |/users/{userId}|ユーザーの退会処理の実行 |
|GET |/games/new |ゲーム開始画面の表示 |
|POST |/games |ゲーム開始処理の実行 |
|GET |/games/{gameId}|ゲーム画面の表示 |
|POST |/games/{gameId}/finish |ゲーム終了処理の実行 |
|GET |/games/{gameId}/result|ゲーム結果画面の表示 |
|POST |/games/{gameId}/post |ゲーム結果のSNS投稿処理の実行 |
|GET |/methods|出題されたメソッド一覧画面の表示 |
|GET |/methods/{methodId}|メソッド詳細画面（モーダル）の表示 |
|GET |/methods/all|これまで出題された全メソッド一覧画面の表示 |
|GET |/official_document|公式ドキュメントリダイレクト処理 |
|GET |/how_to_play|遊び方画面（モーダル）の表示 |
|GET |/terms|利用規約・プライバシーポリシー画面の表示 |

</div></details>

<details><summary>2回目の提出物</summary><div>

| Method| Path | Description |
|:----|:----|:----|
|GET |/ |トップ画面を表示（ログインしていればマイページを、ログインしていなければトップページを表示） |
|GET |/signup |ユーザー登録画面の表示 |
|POST |/signup |ユーザー登録処理の実行 |
|GET |/login|ログイン画面の表示 |
|POST |/login|ログイン処理の実行 |
|POST |/logout|ログアウト処理の実行 |
|GET |/password_resets/new|パスワード再設定用メールアドレス入力画面の表示 |
|POST |/password_resets|パスワード再設定メールの送信処理の実行 |
|GET |/password_resets/{token}/edit|新しいパスワード入力画面の表示 |
|PATCH |/password_resets/{token}|新しいパスワードでの更新処理の実行 |
|GET |/users/{userId}|ユーザー詳細画面の表示（マイページ） |
|GET |/users/{userId}/edit|ユーザー情報編集画面の表示 |
|PATCH |/users/{userId}|ユーザー情報更新処理の実行 |
|DELETE |/users/{userId}|ユーザーの退会処理の実行 |
|GET |/games/new |ゲーム開始画面の表示 |
|POST |/games |ゲーム開始処理の実行 |
|POST |/games/{gameId}/pause|ゲーム中断処理の実行 |
|POST |/games/{gameId}/finish |ゲーム終了処理の実行 |
|GET |/games/{gameId}/result|ゲーム結果画面の表示 |
|POST |/games/{gameId}/post |ゲーム結果のSNS投稿処理の実行 |
| GET | /games/{gameId}/methods | 今回のゲームで出題されたメソッド一覧の表示 |
| GET | /methods | これまで出題された全メソッド一覧画面の表示 |
|GET |/methods/{methodId}|メソッド詳細画面（モーダル）の表示 |
|GET |/official_document|公式ドキュメントリダイレクト処理 |
|GET |/how_to_play|遊び方画面（モーダル）の表示 |
|GET |/terms|利用規約・プライバシーポリシー画面の表示 |

</div></details>

<details><summary>3回目の提出物</summary><div>

| Method| Path | Description |
|:----|:----|:----|
|GET |/ |トップ画面を表示（ログインしていればマイページを、ログインしていなければトップページを表示） |
|GET |/signup |ユーザー登録画面の表示 |
|POST |/signup |ユーザー登録処理の実行 |
|GET |/login|ログイン画面の表示 |
|POST |/login|ログイン処理の実行 |
|POST |/logout|ログアウト処理の実行 |
|GET |/password_resets/new|パスワード再設定用メールアドレス入力画面の表示 |
|POST |/password_resets|パスワード再設定メールの送信処理の実行 |
|GET |/password_resets/{token}/edit|新しいパスワード入力画面の表示 |
|PATCH |/password_resets/{token}|新しいパスワードでの更新処理の実行 |
|GET |/users/{userId}|ユーザー詳細画面の表示（マイページ） |
|GET |/users/{userId}/edit|ユーザー情報編集画面の表示 |
|PATCH |/users/{userId}|ユーザー情報更新処理の実行 |
|DELETE |/users/{userId}|ユーザーの退会処理の実行 |
|GET |/games/new |ゲーム開始画面の表示 |
|POST |/games |ゲーム開始処理の実行 |
|GET |/games/{gameId} |ゲーム画面の表示（ゲーム中）or 結果画面の表示（ゲーム終了後） |
|POST |/games/{gameId}/pause_timer|タイマー一時停止処理の実行 |
|POST |/games/{gameId}/resume_timer|タイマー再開処理の実行 |
|POST |/games/{gameId}/finish |ゲーム終了処理の実行 |
|POST |/games/{gameId}/post |ゲーム結果のSNS投稿処理の実行 |
| GET | /games/{gameId}/methods | 今回のゲームで出題されたメソッド一覧の表示 |
| GET | /methods | これまで出題された全メソッド一覧画面の表示 |
|GET |/methods/{methodId}|メソッド詳細画面（モーダル）の表示 |
|GET |/official_document|公式ドキュメントリダイレクト処理 |
|GET |/how_to_play|遊び方画面（モーダル）の表示 |
|GET |/terms|利用規約・プライバシーポリシー画面の表示 |

</div></details>

| Method| Path | Description |
|:----|:----|:----|
|GET |/ |トップ画面を表示（ログインしていればマイページを、ログインしていなければトップページを表示） |
|GET |/signup |ユーザー登録画面の表示 |
|POST |/signup |ユーザー登録処理の実行 |
|GET |/login|ログイン画面の表示 |
|POST |/login|ログイン処理の実行 |
|POST |/logout|ログアウト処理の実行 |
|GET |/password_resets/new|パスワード再設定用メールアドレス入力画面の表示 |
|POST |/password_resets|パスワード再設定メールの送信処理の実行 |
|GET |/password_resets/{token}/edit|新しいパスワード入力画面の表示 |
|PATCH |/password_resets/{token}|新しいパスワードでの更新処理の実行 |
|GET |/users/{userId}|ユーザー詳細画面の表示（マイページ） |
|GET |/users/{userId}/edit|ユーザー情報編集画面の表示 |
|PATCH |/users/{userId}|ユーザー情報更新処理の実行 |
|DELETE |/users/{userId}|ユーザーの退会処理の実行 |
|GET |/games/new |ゲーム開始画面の表示 |
|POST |/games |ゲーム開始処理の実行 |
|GET |/games/{gameId} |ゲーム画面の表示（ゲーム中）or 結果画面の表示（ゲーム終了後） |
|POST |/games/{gameId}/finish |ゲーム終了処理の実行 |
|POST |/games/{gameId}/post |ゲーム結果のSNS投稿処理の実行 |
| GET | /games/{gameId}/methods | 今回のゲームで出題されたメソッド一覧の表示 |
| GET | /methods | これまで出題された全メソッド一覧画面の表示 |
|GET |/methods/{methodId}|メソッド詳細画面（モーダル）の表示 |
|GET |/official_document|公式ドキュメントリダイレクト処理 |
|GET |/how_to_play|遊び方画面（モーダル）の表示 |
|GET |/terms|利用規約・プライバシーポリシー画面の表示 |

### 備考
- ログイン機能
    - deviseを使用

**Comment by yuuu** [comment]
確認しました 👍 気になった点についてコメントしますので確認をお願いします 🙏 

- 「ゲーム画面の表示」について、GETで閲覧できるようになっていますが、これはゲーム中に画面をリロードしたら再度ゲームに戻ってこれる仕様ということでしょうか？
    - 「ゲーム結果画面の表示」は別途用意されているようなので、このエンドポイントをどういうシチュエーションで利用するのかが読み取れませんでした 🤔 
- ユーザーが見える画面は一通り揃ってそうですが、管理者用の画面は不要でしょうか？
    - 例えば「メソッドの新規登録画面」などは不要でしょうか？
- `/methods` と `/methods/all` を分けているのはなぜでしょうか？
    - 今回出題されたメソッドとこれまで出題されたメソッドのタブごとにエンドポイントを分けている、ということでしょうか？
    - 今回出題されたメソッドは「ゲームに属するメソッド」と解釈できるので、Pathもそれがわかる構造にしたほうが良いですね。

**Comment by yuuu** [comment]
@natsuto6 
回答・修正ありがとうございます 🙏 
概ね問題ないと思いますが、ゲーム開始時の流れだけ確認させてください。以下であっていますでしょうか？

1. `/games/new` にアクセスし、ゲーム開始画面が開く
2. ゲーム開始ボタンをクリックすると `/games` へPOSTしてゲームが開始される。
3. 中断ボタンをクリックすると `/games/{gameId}/pause` へPOSTしてしてゲームが中断される。
4. ゲームが終了すると `/games/{gameId}/finish` へPOSTしてゲームが終了し、 `/games/{gameId}/result` へリダイレクトされる

気になっている点は以下です。

- 2のレスポンスはredirectかrenderか→おそらくrenderなのかなと推察しています。renderだとすると、ゲーム中に画面をリロードすると `GET /games` をすることになり404が返ってくると思いますが認識あっていますでしょうか？
- 3のレスポンスは何が返ってくるでしょうか？
- `/games/{gameId}/result` は ``/games/{gameId}` が使えると思ったのですがどうでしょうか？

**Comment by yuuu** [comment]
DB設計を見ていて、追加で質問です。ユーザーごとにゲーム中断をN個作れる、という理解であっていますでしょうか？
だとすると、中断したゲームの一覧のような画面がないと、ゲームを再開する導線がないのでは？という点が気になっています。ペーパープロトタイプも拝見しましたが、ゲーム中断について特に言及がないようです。

**Comment by natsuto6** [comment]
@yuuu 
ご確認いただきありがとうございます🙏
改めて設計を見直しましたので、お手数ですがご確認よろしくお願いいたします。
以前machidaさんと仕様の擦り合わせをした際のメモをご連携いたします。あらかじめ提示できておらず申し訳ございません🙇‍♂️

<details><summary>machidaさんとの仕様擦り合わせ内容</summary><div>

- 前提
    - 目的はあくまで「タイピングが早くなること」
    - ターゲットは「Ruby学習者」で上級者Rubyistではない。

- 仕様
    - ユーザーは登録しなくてもゲームをプレイできる。
    - PCでオフラインで使用する機会はないから、オフラインでのプレイは不可。
    - Rubyの教材とかによく出てくるメソッドを厳選。（基礎的すぎてもよくない）
    - BGMや効果音、タイプ音、ミス音はいらない。リリース後、ユーザーからのフィードバックがあれば追加。
    - ゲームの難易度を選択できる形式はいらない。将来的に難易度別のゲームを導入する場合は、設計を見直す。（そもそも難易度別として作成することが良いとも限らない）
    - 他人との比較機能はいらない。
    - 結果画面に「X（旧：Twitter）でPostする（つぶやく）」ボタンを追加する。
    - スマホ、タブレット対応はなし。
    - いつでもタイピングを終了・中断できる機能をつける。（ユーザーがどんな目的でタイピングをしているかはケースバイケースだから。escキーとか）
    - ユーザー個人の成長の可視化（前回との比較のみ。それよりも過去の成績はいらない）
    - 例えばshift + dで説明モードに切り替わるようにする。
    - タイマーがストップする機能と画面がモーダルで切り替わる機能が必要。
    - 出題されたメソッド一覧（ログイン済）画面の場合、「今回出題されたメソッド」と「これまで出題されたメソッド」の2つのタブで表示。未ログイン時かつタイピング実施後のマイページから遷移時には「今回出題されたメソッド」のみを表示。
    - タイピング結果画面（ログイン済）の場合、ベストスコアを表示する。未ログイン、ログインに関わらず、ベストスコアを出せなかった場合は実施したタイピングゲームのスコアを表示する。
    - タイピング実施後に表示されるマイページではログインしているユーザーの場合、今回の結果と前回の結果のみを保持し、xxxx年xx月xx日時点の最高得点も表示。会員登録していない（ログインしていない）かつタイピングを未実施のユーザーは何も表示されない。もちろん一回でも実施すれば実施した分の結果が表示される。

- あると便利だけどとりあえずいらない
    - localstorageに成績の保存。これは会員登録しなくてもできてしまうから。

</div></details>

以下、回答いたします。

##### ゲーム開始時の流れについて、
- 2のゲーム開始処理（`POST /games`）のレスポンスについてはrenderではなくredirectが適切かと考えました。理由としては以下です。
    - `GET /games/{gameId}`（こちら追記しました）が呼び出され、ゲーム画面が表示される
    - ゲーム中に画面をリロードしても、`GET /games/{gameId}`が呼び出されるため、ゲームを再開できる
- 3のレスポンスについて、今回の設計では中断ボタンを設けておりません。`shift + D`でメソッドの解説モーダルを表示し、その間はタイマーを一時停止する仕様としてます。

> /games/{gameId}/result は ``/games/{gameId}` が使えると思ったのですがどうでしょうか？

- ゲーム結果画面のURLについて、ご指摘の通り`/games/{gameId}/result`ではなく、`/games/{gameId}`を使用してゲーム結果を表示するよう修正しました。

##### ゲームの中断の再開ついて、
> DB設計を見ていて、追加で質問です。ユーザーごとにゲーム中断をN個作れる、という理解であっていますでしょうか？

- 今回のアプリではユーザーが同時に複数のゲームを中断する必要性は低いと考えました。ユーザーは一度に1つのゲームしか出来ず、新しいゲームを開始すると、中断中のゲームは削除されるのが自然かと考えました。なので中断したゲームの一覧のような画面は不要としております。
- `shift + D`でメソッドの解説モーダルを表示し、その間はタイマーを一時停止する仕様にしてます（ゲームを途中で終了した場合は、そのゲームの記録は保存されない）

**Comment by yuuu** [comment]
@natsuto6 
仕様の検討ありがとうございます 👍 

> 3のレスポンスについて、今回の設計では中断ボタンを設けておりません。shift + Dでメソッドの解説モーダルを表示し、その間はタイマーを一時停止する仕様としてます。

この仕様について、中断の開始・終了時にPOSTリクエストをする想定という理解であっていますか？(それとも中断の開始・終了時にはリクエストを飛ばさずフロントエンドで処理しますか？)

もし、前者の想定で合っている場合、中断の開始時刻・終了時刻を中断ごとに記録する必要があると推察しています。なので、DB設計としては1つのゲームに中断がN個必要となるのではないでしょうか？

**Comment by natsuto6** [comment]
@yuuu 
ご指摘いただきありがとうございます！
リソース設計を再度修正しましたのでお手数ですが再度ご確認をお願いいたします🙇‍♂️

> この仕様について、中断の開始・終了時にPOSTリクエストをする想定という理解であっていますか？(それとも中断の開始・終了時にはリクエストを飛ばさずフロントエンドで処理しますか？)

こちら後者の形をとろうかと考えました。リアルタイムな反応が求められると思うので、中断・再開の処理はフロントエンドで行おうと思います。
なので`/games/{gameId}/pause_timer`と`/games/{gameId}/resume_timer`を削除しました。

**Comment by yuuu** [comment]
@natsuto6 
回答ありがとうございます 👍 なるほど、これらのPathは不要だったということですね。ちなみに、DB設計側で `Games` テーブルに `started_at` `finished_at` というカラムがありますが、長期間ゲームが中断するとゲーム時間が非常に長くなる可能性があります。それでも特に問題はないと考えてよいでしょうか？

**Comment by natsuto6** [comment]
@yuuu 
ご指摘ありがとうございます🙇‍♂️
当初、`started_at`と`finished_at`カラムをゲームの進行状況を管理するために記載していましたが、改めて検討した結果、このタイピングゲームにおいては重要ではないと判断しました（ゲーム時間の長さよりも、正確性やタイピング速度が重要な評価指標となるため）
なので、この2つのカラムを削除することにしました。長期間のゲーム中断に関する懸念についても解消されるかと思います。お手数ですが再度修正後のデータ設計をご確認いただけますでしょうか。よろしくお願いいたします🙇‍♂️
